### ISSUE TITLE
Build for the aarch64 platform

### ISSUE THREAD

**Issue by mathbunnyru** [conda-forge/r-yardstick-feedstock#13]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: I would like to have `r-yardstick` for the aarch64 platform.
Right now I get this problem:
```
 > [4/6] RUN mamba install r-yardstick==0.0.9:

#7 7.148
#7 7.148
#7 7.148 Looking for: ['r-yardstick==0.0.9']
#7 7.148
#7 7.148
#7 7.148 Pinned packages:
#7 7.148   - python 3.9.*
#7 7.148   - python 3.9.7
#7 7.148
#7 7.148
#7 7.148 Encountered problems while solving:
#7 7.148   - nothing provides requested r-yardstick 0.0.9
#7 7.148
#7 7.148 conda-forge/linux-aarch6
#7 7.148 conda-forge/noarch
```

**Comment by mathbunnyru** [comment]
I've opened a PR to start the process: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4078

**Comment by mfansler** [comment]
If v0.0.9 is specifically needed, then we'll also have to do an extra off-`main` build once the migration merges. Migration only builds the latest version.

**Comment by mathbunnyru** [comment]
I think only the latest version should be enough.

**Comment by mathbunnyru** [comment]
Done in https://github.com/conda-forge/r-yardstick-feedstock/pull/17
